defmodule AshMqtt.BrokerConfig.MosquittoTest do
  use ExUnit.Case, async: true

  alias AshMqtt.BrokerConfig.Mosquitto
  alias AshMqtt.Test.Fixtures.{Device, DeviceShadow}

  describe "render/2" do
    test "starts with a generated-by header that names the resources" do
      out = Mosquitto.render([Device])
      assert out =~ "Generated by AshMqtt.BrokerConfig.Mosquitto."
      assert out =~ "Resources: AshMqtt.Test.Fixtures.Device"
    end

    test "emits one pattern line per topic with the right mode" do
      out = Mosquitto.render([Device])

      assert out =~ "pattern read tenants/%u/devices/%c/cmd"
      assert out =~ "pattern write tenants/%u/devices/%c/up"
      assert out =~ "pattern write tenants/%u/devices/%c/state"
    end

    test "emits readwrite for actions and the reply subtopic when reply: true" do
      out = Mosquitto.render([Device])

      assert out =~ "pattern readwrite tenants/%u/devices/%c/cmd/reboot"
      assert out =~ "pattern readwrite tenants/%u/devices/%c/cmd/read_config"
      # read_config has reply: true → an extra reply subtopic ACL
      assert out =~ "pattern readwrite tenants/%u/devices/%c/cmd/read_config/reply/+"
    end

    test "ends with a newline" do
      out = Mosquitto.render([Device])
      assert String.ends_with?(out, "\n")
    end

    test "includes shadow topics when a shadow-using resource is in the list" do
      out = Mosquitto.render([DeviceShadow])

      assert out =~ "pattern read tenants/%u/devices/%c/shadow/desired"
      assert out =~ "pattern read tenants/%u/devices/%c/shadow/delta"
      assert out =~ "pattern read tenants/%u/devices/%c/shadow/get"
      assert out =~ "pattern write tenants/%u/devices/%c/shadow/reported"
    end

    test "honours :public_subscribe ACL with two-line emission" do
      defmodule PublicResource do
        use Ash.Resource,
          domain: AshMqtt.Test.Fixtures.Domain,
          data_layer: Ash.DataLayer.Ets,
          extensions: [AshMqtt.Resource]

        attributes do
          uuid_primary_key :id
        end

        actions do
          defaults [:read, :destroy, :create]
        end

        mqtt do
          acl(:public_subscribe)
          topic("broadcast/:topic", as: :broadcast, direction: :outbound)
        end
      end

      out = Mosquitto.render([PublicResource])
      assert out =~ "topic read broadcast/+"
      assert out =~ "pattern write broadcast/+"
    end
  end
end
