defmodule AshMqtt.BrokerConfig.Mosquitto do
  @moduledoc """
  Render an MQTT-enabled set of resources to a Mosquitto ACL file.

  The output is in the standard Mosquitto `acl_file` format:

      # comment
      user <username-pattern-or-name>
      topic <readwrite|read|write|deny> <topic-filter>
      ...

  Mosquitto's pattern variables (`%u` for username, `%c` for client id)
  are substituted from `:tenant_id` / `:device_id` placeholders. Other
  placeholders become `+` (single-level wildcard).

  ## ACL policies

    * `:tenant_isolated` — emits a `pattern` block (applies to every
      authenticated user) where each user's tenant is enforced via `%u`
      and the device id via `%c`. This is the default and what most
      device topics use.
    * `:device_owned` — like `:tenant_isolated` but stricter: read+write
      both go through `%c`-bound topics; this enforces per-device
      isolation in addition to per-tenant.
    * `:public_subscribe` — every authenticated user may subscribe; only
      the matching tenant may publish.
    * `:public_publish` — every authenticated user may publish; the
      tenant scope still gates subscribe.

  The `direction:` declared on a topic (or action) constrains read vs.
  write:

    * `:inbound`        — backend → device. Devices subscribe, backend
      publishes. ACL grants `read` to devices.
    * `:outbound`       — device → backend. Devices publish, backend
      subscribes. ACL grants `write` to devices.
    * `:bidirectional`  — both. ACL grants `readwrite`.
  """

  alias AshMqtt.BrokerConfig
  alias AshMqtt.Resource.{Action, Info, Topic}

  @doc """
  Render an ACL file body for a list of resources.

  Output ends with a newline. The header is a comment naming the
  generator and the resource list so the file can be sanity-checked at
  the broker.
  """
  @spec render([module()], keyword()) :: String.t()
  def render(resources, opts \\ []) when is_list(resources) do
    header = Keyword.get(opts, :header, default_header(resources))

    body =
      resources
      |> Enum.map(&resource_block/1)
      |> Enum.join("\n")

    header <> body <> "\n"
  end

  defp default_header(resources) do
    list = Enum.map_join(resources, ", ", &inspect/1)

    """
    # Generated by AshMqtt.BrokerConfig.Mosquitto.
    # Resources: #{list}
    # Edit the resource declarations, not this file.

    """
  end

  defp resource_block(resource) do
    sections =
      [
        resource_topics_block(resource),
        resource_actions_block(resource)
      ]
      |> Enum.reject(&(&1 == ""))
      |> Enum.join("\n")

    "# resource: #{inspect(resource)}\n" <> sections
  end

  defp resource_topics_block(resource) do
    case BrokerConfig.topics(resource) do
      [] ->
        ""

      topics ->
        Enum.map_join(topics, "\n", &topic_lines(resource, &1)) <> "\n"
    end
  end

  defp resource_actions_block(resource) do
    case BrokerConfig.actions(resource) do
      [] ->
        ""

      actions ->
        # Actions are bidirectional from a topic-ACL perspective: requests come
        # in (inbound) and replies go back if `reply: true`.
        Enum.map_join(actions, "\n", &action_lines(resource, &1)) <> "\n"
    end
  end

  defp topic_lines(resource, %Topic{} = topic) do
    filter = AshMqtt.Topic.render(topic.pattern, :mosquitto)
    acl = Info.effective_acl(resource, topic)
    mode = direction_to_mode(topic.direction)
    emit_acl_lines(filter, acl, mode, topic)
  end

  defp action_lines(resource, %Action{topic: pattern, reply: reply?}) do
    filter = AshMqtt.Topic.render(pattern, :mosquitto)
    acl = Info.mqtt_acl!(resource)

    base = emit_acl_lines(filter, acl, :readwrite, %{direction: :bidirectional})

    if reply? do
      base <> "\n" <> emit_acl_lines(filter <> "/reply/+", acl, :readwrite, %{direction: :bidirectional})
    else
      base
    end
  end

  # `direction` translates to a single ACL mode for the device side.
  defp direction_to_mode(:inbound), do: :read
  defp direction_to_mode(:outbound), do: :write
  defp direction_to_mode(:bidirectional), do: :readwrite
  defp direction_to_mode(nil), do: :readwrite

  defp emit_acl_lines(filter, :tenant_isolated, mode, _ctx) do
    "pattern #{mode_keyword(mode)} #{filter}"
  end

  defp emit_acl_lines(filter, :device_owned, mode, _ctx) do
    # Mosquitto's `pattern` form already substitutes %c; under
    # device_owned we use the same template but additionally hint with a
    # comment so operators reading the file see the intent.
    "# device_owned (each %c only sees its own topics)\n" <>
      "pattern #{mode_keyword(mode)} #{filter}"
  end

  defp emit_acl_lines(filter, :public_subscribe, _mode, _ctx) do
    # Anyone can read; only the tenant may publish.
    "topic read #{filter}\n" <>
      "pattern write #{filter}"
  end

  defp emit_acl_lines(filter, :public_publish, _mode, _ctx) do
    "topic write #{filter}\n" <>
      "pattern read #{filter}"
  end

  defp mode_keyword(:read), do: "read"
  defp mode_keyword(:write), do: "write"
  defp mode_keyword(:readwrite), do: "readwrite"
end
